### ISSUE TITLE
Bug with handling of falsey values

### ISSUE THREAD

**Issue by plowman** [lil-js/uri#11]
Hey there,

I'm using your library in react native because it's missing the `URLSearchParams` that would normally be useful for this stuff. For simple stuff it works well, but for more complicated stuff it starts to have trouble.

Here's what I'm seeing:
```
import uri from 'lil-uri';
const url = uri()
      .query({
        'zero': 0,
        'one': 1,
        'zero_str': '0',
        'one_str': '1',
        'true': true,
        'false': false,
      })
      .build();
```

I'd expect that to output:
```
"/?zero=0&one=1&zero_str=0&one_str=1&true=true&false=false"
```

Instead I get:
```
"/?zero&one=1&zero_str=0&one_str=1&true=true&false"
```

**Comment by h2non** [comment]
It should be fixed in `master`. Can you try updating from it before the `npm` publish?
`yarn add lil-js/uri#master`

**Comment by plowman** [comment]
Hey @h2non thanks for the fast fix! It seems to have worked for me.

**Comment by h2non** [comment]
Cool, I will push a new release on npm later today.
