### ISSUE TITLE
BUG - uri errors when non-UTF8 chars in url

### ISSUE THREAD

**Issue by froog** [lil-js/uri#7]
Because uri uses decodeURIComponent, it throws an error if a non-UTF8 char is set in the URL, eg;

uri('http://example.com?x=%92')

> Uncaught URIError: URI malformed

**Comment by h2non** [comment]
Thanks for reporting. It was just fixed in `v0.2.1`. Feel free to update the package via `npm` or `bower`.

**Comment by Kreijstal** [comment]
This breaks umlaut characters on strings. Please see https://github.com/lil-js/uri/commit/bf5b662178c3323e1517a69fd964e5f0f3fe4146#commitcomment-46302676
