### ISSUE TITLE
How to use in Browser

### ISSUE THREAD

**Issue by RobDaPraia** [lil-js/uri#9]
Hi,

Thanks for this library.

Can you please explain or give an example of how to use this code in a browser?

I use the following code, but get an error 'uri is not defined'

```
<script src="../../Scripts/uri.js"></script>

<script type="text/javascript">

    console.log('window.location: ' + window.location);
    var url = uri(window.location);
    console.log('url.query(): ' + url.query());
</script>
```

**Comment by h2non** [comment]
Use `lil.uri`.

**Comment by RobDaPraia** [comment]
Thanks for the quick reply

Found out that there was also another error, 'window.location' is an object while the uri function wants a string. The following code is now working:

```
var url = lil.uri(window.location.toString());
console.log('url.search(): ' + url.search());
```
